import os

TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = os.environ.get("TELEGRAM_CHAT_ID", "")

WATCHLIST = [
    "AAPL", "MSFT", "NVDA", "AMZN", "TSLA",
    "SAP.DE", "ASML.AS", "MC.PA",
]

DAILY_SCREEN_UNIVERSE = WATCHLIST + [
    "GOOGL", "META", "AMD", "NFLX", "JPM", "XOM",
    "SIE.DE", "AIR.PA", "OR.PA",
]

TIMEFRAMES = ["5m", "15m"]

SMA_FAST = 20
SMA_SLOW = 50
EMA_FAST = 9
EMA_SLOW = 21
RSI_PERIOD = 14
RSI_OVERSOLD = 30
RSI_OVERBOUGHT = 70
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9
BB_PERIOD = 20
BB_STD = 2
VOLUME_LOOKBACK = 20
VOLUME_SPIKE_MULTIPLIER = 1.5

MIN_SIGNAL_SCORE = 4

ACCOUNT_BALANCE_EUR = 3000
RISK_PER_TRADE_PCT = 1.0
TARGET_PROFIT_EUR = 100
